"use client";

import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { AppShell, Card, PageHeading, StatusBadge } from "@/components/marketeros-shell";
import type { ApiResponse } from "@/lib/api-contracts";
import type { Lead } from "@/lib/types";

export function LiveLeadsPage({ detailId }: { detailId?: string }) {
  const [items, setItems] = useState<Lead[]>([]); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState({ firstName: "", lastName: "", email: "", company: "", source: "Manual" });
  async function load() { const response = await fetch("/api/v1/leads"); const payload = await response.json() as ApiResponse<{ items: Lead[] }>; if (!response.ok) throw new Error(payload.error?.message || "Unable to load leads."); setItems(payload.data.items); }
  useEffect(() => { load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load leads.")); }, []);
  async function create() { const response = await fetch("/api/v1/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || "Unable to create lead."); setOpen(false); setForm({ firstName: "", lastName: "", email: "", company: "", source: "Manual" }); await load(); }
  const lead = detailId ? items.find((item) => item.id === detailId) : null;
  if (detailId) return <AppShell title="Leads"><Card>{lead ? <><PageHeading title={lead.name} description={`${lead.company} · ${lead.source}`} /><div className="mt-5 grid gap-4 sm:grid-cols-4 text-xs"><div><span className="text-[#8490a4]">Status</span><div className="mt-1"><StatusBadge status={lead.status} /></div></div><div><span className="text-[#8490a4]">Score</span><strong className="mt-1 block">{lead.score}</strong></div><div><span className="text-[#8490a4]">Owner</span><strong className="mt-1 block">{lead.owner}</strong></div><div><span className="text-[#8490a4]">Revenue</span><strong className="mt-1 block">${lead.revenue.toLocaleString()}</strong></div></div></> : <PageHeading title="Lead not found" description={error || "The lead is not available in this workspace."} />}</Card></AppShell>;
  return <AppShell title="Leads" action={<button onClick={() => setOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-gradient-to-r from-[#6937e7] to-[#7445ed] px-3.5 text-xs font-bold text-white"><Plus size={15} />Add Lead</button>}><PageHeading title="Leads" description="Track, manage and convert your leads efficiently." />{error && <Card className="mb-4 border-[#f2c4c8] text-xs text-[#b72e38]">{error}</Card>}<Card flush><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-[#edf0f4] text-[10px] uppercase text-[#8490a4]"><th className="px-4 py-3">Lead</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Owner</th></tr></thead><tbody>{items.map((item) => <tr className="border-b border-[#f0f2f6] hover:bg-[#fbfbfe]" key={item.id}><td className="px-4 py-3"><a href={`/leads/${item.id}`} className="font-bold text-[#17223a]">{item.name}</a></td><td className="px-4 py-3">{item.company}</td><td className="px-4 py-3">{item.source}</td><td className="px-4 py-3"><StatusBadge status={item.status} /></td><td className="px-4 py-3">{item.score}</td><td className="px-4 py-3">{item.owner}</td></tr>)}</tbody></table></div>{!items.length && <div className="p-10 text-center text-xs text-[#7d899e]">No leads are available yet.</div>}</Card>{open && <div className="fixed inset-0 z-30 grid place-items-center bg-[#10192d]/30 p-4"><Card className="w-full max-w-lg"><PageHeading title="Add Lead" description="Create a persisted lead in this workspace." /><div className="mt-4 grid gap-3 sm:grid-cols-2">{([["firstName", "First name"], ["lastName", "Last name"], ["email", "Email"], ["company", "Company"], ["source", "Source"]] as const).map(([key, label]) => <label key={key}><span className="mb-1 block text-xs font-bold">{label}</span><input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="h-9 w-full rounded-lg border border-[#dfe3eb] px-2 text-xs" /></label>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setOpen(false)} className="h-9 rounded-lg border border-[#dfe3ea] px-3 text-xs font-bold">Cancel</button><button onClick={() => create().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to create lead."))} className="h-9 rounded-lg bg-[#6940e8] px-3 text-xs font-bold text-white">Create Lead</button></div></Card></div>}</AppShell>;
}
