"use client";

import { useEffect, useState } from "react";
import { FileBarChart, Plus, Sparkles } from "lucide-react";
import { AppShell, Card, PageHeading, StatusBadge } from "@/components/marketeros-shell";
import { TrendChart } from "@/components/marketeros-charts";
import type { ApiResponse } from "@/lib/api-contracts";
import type { OverviewPayload } from "@/lib/types";
import { money } from "@/lib/utils";

type Row = { id: string; name?: string; title?: string; status?: string; description?: string; trigger?: string; action?: string; role?: string; email?: string; invoiceNumber?: string; total?: unknown; invoiceDate?: string };
async function getItems(path: string) { const response = await fetch(`/api/v1/${path}`); const payload = await response.json() as ApiResponse<{ items: Row[] }>; if (!response.ok) throw new Error(payload.error?.message || `Unable to load ${path}.`); return payload.data.items || []; }

export function LiveAnalyticsPage() {
  const [data, setData] = useState<OverviewPayload | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/v1/analytics/overview").then(async (response) => { const payload = await response.json() as ApiResponse<OverviewPayload>; if (!response.ok) throw new Error(payload.error?.message || "Unable to load analytics."); return payload.data; }).then(setData).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load analytics.")); }, []);
  return <AppShell title="Analytics"><PageHeading title="Analytics" description="Track performance across all persisted campaigns and platforms." />{error && <Card className="border-[#f2c4c8] text-xs text-[#b72e38]">{error}</Card>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{data?.kpis.map((metric) => <Card className="p-4" key={metric.label}><div className="text-[11px] text-[#58657d]">{metric.label}</div><div className="mt-2 text-2xl font-extrabold">{metric.value}</div><div className="mt-1 text-[10px] text-[#159a65]">{metric.change}</div></Card>)}</div><div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><Card><div className="text-sm font-extrabold">Performance Over Time</div>{data?.series.length ? <TrendChart data={data.series} showRoas /> : <div className="grid h-48 place-items-center text-xs text-[#7d899e]">No metrics have been synced.</div>}</Card><Card><div className="text-sm font-extrabold">Spend by Platform</div><div className="mt-4 space-y-3">{data?.platformSpend.map((item) => <div className="flex justify-between text-xs" key={item.label}><span>{item.label}</span><strong>{money(item.value)} ({item.percent}%)</strong></div>)}</div></Card></div></AppShell>;
}

export function LiveAdManagerPage() { const [items, setItems] = useState<Row[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { getItems("campaigns").then(setItems).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load campaigns.")); }, []); return <AppShell title="Ad Manager"><PageHeading title="Ad Manager" description="Create, manage, and optimize persisted advertising campaigns." />{error && <Card className="border-[#f2c4c8] text-xs text-[#b72e38]">{error}</Card>}<Card flush><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-[#edf0f4] text-[10px] uppercase text-[#8490a4]"><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Platform</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Spend</th><th className="px-4 py-3">Conversions</th></tr></thead><tbody>{items.map((item) => <tr className="border-b border-[#f0f2f6]" key={item.id}><td className="px-4 py-3 font-bold"><a href={`/campaigns/${item.id}`}>{item.name}</a></td><td className="px-4 py-3">{item.description || "—"}</td><td className="px-4 py-3"><StatusBadge status={item.status || "Draft"} /></td><td className="px-4 py-3">Live campaign metrics</td><td className="px-4 py-3">Synced by provider</td></tr>)}</tbody></table></div>{!items.length && <div className="p-10 text-center text-xs text-[#7d899e]">No campaigns are available.</div>}</Card></AppShell>; }

export function LiveReportsPage() {
  const [items, setItems] = useState<Row[]>([]); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { setItems(await getItems("reports")); }
  useEffect(() => { load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load reports.")); }, []);
  async function create() { setBusy(true); const response = await fetch("/api/v1/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: name || "Marketing performance report" }) }); const payload = await response.json(); setBusy(false); if (!response.ok) setError(payload.error?.message || "Unable to generate report."); else { setName(""); await load(); } }
  return <AppShell title="Reports" action={<button onClick={create} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg bg-gradient-to-r from-[#6937e7] to-[#7445ed] px-3.5 text-xs font-bold text-white"><Plus size={15} />{busy ? "Generating…" : "Generate Report"}</button>}><PageHeading title="Reports" description="Generate and monitor persisted reports." /><Card><div className="flex gap-2"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Report name" className="h-9 flex-1 rounded-lg border border-[#dfe3eb] px-3 text-xs" /><button onClick={create} className="h-9 rounded-lg border border-[#dfe3eb] px-3 text-xs font-bold">Create</button></div>{error && <p className="mt-3 text-xs text-[#b72e38]">{error}</p>}<div className="mt-5 divide-y divide-[#edf0f4]">{items.map((item) => <div className="flex items-center justify-between py-3 text-xs" key={item.id}><span className="font-bold">{item.name}</span><StatusBadge status={item.status || "Draft"} /></div>)}{!items.length && <div className="p-8 text-center text-xs text-[#7d899e]">No reports have been generated.</div>}</div></Card></AppShell>;
}

export function LiveAutomationPage() {
  const [items, setItems] = useState<Row[]>([]); const [form, setForm] = useState({ name: "", trigger: "campaign.metric", action: "notify" }); const [error, setError] = useState<string | null>(null);
  async function load() { setItems(await getItems("automation")); }
  useEffect(() => { load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load automation.")); }, []);
  async function create() { const response = await fetch("/api/v1/automation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) setError(payload.error?.message || "Unable to create automation."); else { setForm({ ...form, name: "" }); await load(); } }
  return <AppShell title="Automation" action={<button onClick={create} className="inline-flex h-9 items-center gap-2 rounded-lg bg-gradient-to-r from-[#6937e7] to-[#7445ed] px-3.5 text-xs font-bold text-white"><Plus size={15} />Create Automation</button>}><PageHeading title="Automation" description="Evaluate persisted rules against workspace marketing data." /><Card><div className="grid gap-3 md:grid-cols-3"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Automation name" className="h-9 rounded-lg border border-[#dfe3eb] px-3 text-xs" /><input value={form.trigger} onChange={(event) => setForm({ ...form, trigger: event.target.value })} placeholder="Trigger" className="h-9 rounded-lg border border-[#dfe3eb] px-3 text-xs" /><input value={form.action} onChange={(event) => setForm({ ...form, action: event.target.value })} placeholder="Action" className="h-9 rounded-lg border border-[#dfe3eb] px-3 text-xs" /></div>{error && <p className="mt-3 text-xs text-[#b72e38]">{error}</p>}<div className="mt-5 divide-y divide-[#edf0f4]">{items.map((item) => <div className="flex items-center justify-between py-3 text-xs" key={item.id}><span className="font-bold">{item.name}</span><span className="text-[#7d899e]">{item.trigger} → {item.action}</span></div>)}{!items.length && <div className="p-8 text-center text-xs text-[#7d899e]">No automations configured.</div>}</div></Card></AppShell>;
}

export function LiveClientsPage() { const [items, setItems] = useState<Row[]>([]); useEffect(() => { getItems("clients").then(setItems).catch(() => setItems([])); }, []); return <AppShell title="Clients"><PageHeading title="Clients" description="Manage persisted brands and client performance." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.id}><div className="text-sm font-extrabold">{item.name}</div><div className="mt-2 text-xs text-[#7d899e]">{item.description || "Client workspace"}</div><a href={`/clients/${item.id}`} className="mt-4 inline-block text-xs font-bold text-[#6940e8]">Open client</a></Card>)}{!items.length && <Card className="p-8 text-center text-xs text-[#7d899e] md:col-span-3">No clients are configured.</Card>}</div></AppShell>; }

export function LiveTeamPage() { const [items, setItems] = useState<Row[]>([]); useEffect(() => { getItems("team").then(setItems).catch(() => setItems([])); }, []); return <AppShell title="Team"><PageHeading title="Team" description="Workspace membership and role access." /><Card><div className="divide-y divide-[#edf0f4]">{items.map((item) => <div className="flex items-center justify-between py-3 text-xs" key={item.id}><div><div className="font-bold">{item.name}</div><div className="mt-1 text-[#7d899e]">{item.email}</div></div><div className="text-right"><div className="font-bold">{item.role}</div><div className="mt-1 text-[#7d899e]">{item.status}</div></div></div>)}{!items.length && <div className="p-8 text-center text-xs text-[#7d899e]">No team members are available.</div>}</div><div className="mt-4 rounded-lg border border-[#e3e6ed] bg-[#fafbfe] p-3 text-xs text-[#6f7c92]">Invitations and email delivery are not configured in this release.</div></Card></AppShell>; }

export function LiveContentPage({ ai = false }: { ai?: boolean }) { const [items, setItems] = useState<Row[]>([]); const [prompt, setPrompt] = useState(""); const [output, setOutput] = useState(""); const [error, setError] = useState<string | null>(null); useEffect(() => { getItems("content").then(setItems).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load content.")); }, []); async function generate() { const response = await fetch("/api/v1/ai/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt, kind: "content" }) }); const payload = await response.json(); if (!response.ok) setError(payload.error?.message || "AI is not configured."); else setOutput(payload.data.output); } return <AppShell title={ai ? "AI Content Creator" : "Content Studio"}><PageHeading title={ai ? "AI Content Creator" : "Content Studio"} description="Create and manage content from persisted workspace data." /><Card><div className="flex items-center gap-2"><Sparkles size={17} className="text-[#6940e8]" /><span className="text-sm font-extrabold">{ai ? "Generate content" : "Recent content"}</span></div>{ai && <><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} className="mt-4 h-32 w-full rounded-lg border border-[#dfe3eb] p-3 text-xs" placeholder="Describe the content you want to create…" /><button onClick={generate} className="mt-3 h-9 rounded-lg bg-[#6940e8] px-3 text-xs font-bold text-white">Generate with OpenAI</button>{output && <div className="mt-4 rounded-lg bg-[#f8f9fc] p-4 text-xs whitespace-pre-wrap">{output}</div>}</>} {error && <p className="mt-3 text-xs text-[#b72e38]">{error}</p>}<div className="mt-5 divide-y divide-[#edf0f4]">{items.map((item) => <div className="flex items-center justify-between py-3 text-xs" key={item.id}><span className="font-bold">{item.title}</span><span className="text-[#7d899e]">{item.status}</span></div>)}{!items.length && !ai && <div className="p-8 text-center text-xs text-[#7d899e]">No content has been created.</div>}</div></Card></AppShell>; }
