"use client";

import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { AppShell, Card, PageHeading } from "@/components/marketeros-shell";
import type { ApiResponse } from "@/lib/api-contracts";

type Settings = { id: string; name: string; website?: string | null; industry?: string | null; description?: string | null; country?: string | null; currency: string; timezone: string; monthlyBudget?: unknown; dateFormat: string; timeFormat: string; language: string; theme: string; defaultDashboard: string };
export function LiveSettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/v1/settings").then(async (response) => { const payload = await response.json() as ApiResponse<{ workspace: Settings }>; if (!response.ok) throw new Error(payload.error?.message || "Unable to load settings."); return payload.data.workspace; }).then(setSettings).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load settings.")); }, []);
  async function save() { if (!settings) return; setBusy(true); setSaved(false); const response = await fetch("/api/v1/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); const payload = await response.json(); setBusy(false); if (!response.ok) setError(payload.error?.message || "Unable to save settings."); else { setSettings(payload.data); setSaved(true); } }
  if (!settings) return <AppShell title="Settings"><Card><PageHeading title="Settings" description={error || "Loading workspace settings…"} /></Card></AppShell>;
  return <AppShell title="Settings"><PageHeading title="Workspace Settings" description="Manage the persisted workspace profile and regional preferences." action={<button onClick={save} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg bg-gradient-to-r from-[#6937e7] to-[#7445ed] px-3.5 text-xs font-bold text-white"><Save size={14} />{busy ? "Saving…" : "Save changes"}</button>} />{error && <Card className="mb-4 border-[#f2c4c8] text-xs text-[#b72e38]">{error}</Card>}{saved && <Card className="mb-4 border-[#c8ecd9] bg-[#effbf5] text-xs text-[#148b5a]">Settings saved to PostgreSQL.</Card>}<Card><div className="grid gap-4 sm:grid-cols-2">{([["name", "Workspace name"], ["website", "Website"], ["industry", "Industry"], ["country", "Country"], ["currency", "Currency"], ["timezone", "Timezone"], ["language", "Language"], ["theme", "Theme"]] as const).map(([key, label]) => <label key={key}><span className="mb-1.5 block text-xs font-bold">{label}</span><input value={String(settings[key] || "")} onChange={(event) => setSettings({ ...settings, [key]: event.target.value })} className="h-10 w-full rounded-lg border border-[#dfe3eb] px-3 text-xs outline-none" /></label>)}<label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-bold">Description</span><textarea value={settings.description || ""} onChange={(event) => setSettings({ ...settings, description: event.target.value })} className="h-24 w-full rounded-lg border border-[#dfe3eb] p-3 text-xs outline-none" /></label></div></Card></AppShell>;
}
