import type { Platform } from "@/lib/types";

export type ProviderKey = "google_ads" | "google_analytics" | "google_search_console" | "google_firebase" | "google_admob" | "google_youtube" | "google_business_profile" | "meta_ads" | "meta_facebook" | "meta_instagram" | "meta_messenger" | "meta_whatsapp";
export type NormalizedMetric = { externalId: string; date: string; impressions: number; clicks: number; conversions: number; spend: number; revenue: number };
export type ProviderAccount = { id: string; name: string; platform: Platform; scopes: string[] };
export type ProviderToken = { accessToken: string; refreshToken?: string; expiresAt?: Date; scopes: string[] };

export interface MarketingProvider {
  readonly platform: Platform;
  readonly providerKey: ProviderKey;
  getAuthorizationUrl(state: string, redirectUri: string): string;
  exchangeCode(code: string, redirectUri: string): Promise<ProviderToken>;
  listAccounts(accessToken: string): Promise<ProviderAccount[]>;
  syncMetrics(accessToken: string, accountId: string, from: Date, to: Date): Promise<NormalizedMetric[]>;
}

const googleScopes: Record<ProviderKey, string[]> = {
  google_ads: ["https://www.googleapis.com/auth/adwords"], google_analytics: ["https://www.googleapis.com/auth/analytics.readonly"], google_search_console: ["https://www.googleapis.com/auth/webmasters.readonly"], google_firebase: ["https://www.googleapis.com/auth/firebase.readonly"], google_admob: ["https://www.googleapis.com/auth/admob.readonly"], google_youtube: ["https://www.googleapis.com/auth/youtube.readonly"], google_business_profile: ["https://www.googleapis.com/auth/business.manage"], meta_ads: [], meta_facebook: [], meta_instagram: [], meta_messenger: [], meta_whatsapp: []
};
const metaScopes = ["ads_read", "ads_management", "pages_read_engagement", "pages_manage_posts", "instagram_basic", "instagram_content_publish", "business_management"];

export function providerConfiguration(providerKey: ProviderKey) {
  const required = providerKey.startsWith("google_") ? ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"] : ["META_CLIENT_ID", "META_CLIENT_SECRET"];
  if (providerKey === "google_ads") required.push("GOOGLE_ADS_DEVELOPER_TOKEN");
  return { configured: required.every((name) => Boolean(process.env[name])), missing: required.filter((name) => !process.env[name]) };
}

async function jsonRequest<T>(url: string, init: RequestInit) {
  const response = await fetch(url, { ...init, signal: AbortSignal.timeout(12_000) }); const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof body?.error?.message === "string" ? body.error.message : `Provider request failed with ${response.status}.`);
  return body as T;
}

class GoogleProvider implements MarketingProvider {
  readonly platform: Platform;
  constructor(public readonly providerKey: ProviderKey) { this.platform = providerKey === "google_ads" ? "Google Ads" : providerKey === "google_analytics" ? "Google Analytics" : providerKey === "google_youtube" ? "YouTube" : "Google Analytics"; }
  getAuthorizationUrl(state: string, redirectUri: string) { const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.searchParams.set("client_id", process.env.GOOGLE_CLIENT_ID || ""); url.searchParams.set("redirect_uri", redirectUri); url.searchParams.set("response_type", "code"); url.searchParams.set("access_type", "offline"); url.searchParams.set("prompt", "consent"); url.searchParams.set("scope", googleScopes[this.providerKey].join(" ")); url.searchParams.set("state", state); return url.toString(); }
  async exchangeCode(code: string, redirectUri: string) { const body = await jsonRequest<{ access_token: string; refresh_token?: string; expires_in?: number; scope?: string }>("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: process.env.GOOGLE_CLIENT_ID || "", client_secret: process.env.GOOGLE_CLIENT_SECRET || "", redirect_uri: redirectUri, grant_type: "authorization_code" }) }); return { accessToken: body.access_token, refreshToken: body.refresh_token, expiresAt: body.expires_in ? new Date(Date.now() + body.expires_in * 1000) : undefined, scopes: (body.scope || "").split(" ").filter(Boolean) }; }
  async listAccounts(accessToken: string) { if (this.providerKey === "google_ads") { const body = await jsonRequest<{ resourceNames?: string[] }>("https://googleads.googleapis.com/v18/customers:listAccessibleCustomers", { headers: { authorization: `Bearer ${accessToken}`, "developer-token": process.env.GOOGLE_ADS_DEVELOPER_TOKEN || "", ...(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID ? { "login-customer-id": process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID.replaceAll("-", "") } : {}) } }); return (body.resourceNames || []).map((resource) => ({ id: resource.split("/").pop() || resource, name: `Google Ads customer ${resource.split("/").pop()}`, platform: this.platform, scopes: googleScopes[this.providerKey] })); } const profile = await jsonRequest<{ sub: string; email?: string; name?: string }>("https://openidconnect.googleapis.com/v1/userinfo", { headers: { authorization: `Bearer ${accessToken}` } }); return [{ id: profile.sub, name: profile.name || profile.email || "Google account", platform: this.platform, scopes: googleScopes[this.providerKey] }]; }
  async syncMetrics(accessToken: string, accountId: string, from: Date, to: Date) { if (this.providerKey !== "google_ads") throw new Error(`${this.providerKey} account connected; product metrics sync is not configured for this workspace.`); const customerId = accountId.replaceAll("-", ""); const query = `SELECT segments.date, metrics.impressions, metrics.clicks, metrics.conversions, metrics.cost_micros, metrics.conversions_value FROM customer WHERE segments.date BETWEEN '${from.toISOString().slice(0, 10)}' AND '${to.toISOString().slice(0, 10)}'`; const body = await jsonRequest<Array<{ results?: Array<{ segments?: { date?: string }; metrics?: { impressions?: string; clicks?: string; conversions?: number; costMicros?: string; conversionsValue?: number } }> }>>(`https://googleads.googleapis.com/v18/customers/${customerId}/googleAds:searchStream`, { method: "POST", headers: { authorization: `Bearer ${accessToken}`, "content-type": "application/json", "developer-token": process.env.GOOGLE_ADS_DEVELOPER_TOKEN || "", ...(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID ? { "login-customer-id": process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID.replaceAll("-", "") } : {}) }, body: JSON.stringify({ query }) }); return body.flatMap((batch) => batch.results || []).map((row) => ({ externalId: customerId, date: row.segments?.date || from.toISOString().slice(0, 10), impressions: Number(row.metrics?.impressions || 0), clicks: Number(row.metrics?.clicks || 0), conversions: Number(row.metrics?.conversions || 0), spend: Number(row.metrics?.costMicros || 0) / 1_000_000, revenue: Number(row.metrics?.conversionsValue || 0) })); }
}

class MetaProvider implements MarketingProvider {
  readonly platform: Platform;
  constructor(public readonly providerKey: ProviderKey) { this.platform = providerKey === "meta_instagram" ? "Instagram" : providerKey === "meta_facebook" ? "Facebook" : "Meta Ads"; }
  getAuthorizationUrl(state: string, redirectUri: string) { const url = new URL("https://www.facebook.com/v20.0/dialog/oauth"); url.searchParams.set("client_id", process.env.META_CLIENT_ID || ""); url.searchParams.set("redirect_uri", redirectUri); url.searchParams.set("response_type", "code"); url.searchParams.set("scope", metaScopes.join(",")); url.searchParams.set("state", state); return url.toString(); }
  async exchangeCode(code: string, redirectUri: string) { const url = new URL("https://graph.facebook.com/v20.0/oauth/access_token"); url.searchParams.set("client_id", process.env.META_CLIENT_ID || ""); url.searchParams.set("client_secret", process.env.META_CLIENT_SECRET || ""); url.searchParams.set("redirect_uri", redirectUri); url.searchParams.set("code", code); const body = await jsonRequest<{ access_token: string; expires_in?: number }>(url.toString(), { method: "GET" }); return { accessToken: body.access_token, expiresAt: body.expires_in ? new Date(Date.now() + body.expires_in * 1000) : undefined, scopes: metaScopes }; }
  async listAccounts(accessToken: string) { const endpoint = this.providerKey === "meta_ads" ? "https://graph.facebook.com/v20.0/me/adaccounts?fields=id,name,account_status" : "https://graph.facebook.com/v20.0/me/accounts?fields=id,name"; const body = await jsonRequest<{ data?: Array<{ id: string; name?: string }> }>(endpoint, { headers: { authorization: `Bearer ${accessToken}` } }); return (body.data || []).map((account) => ({ id: account.id, name: account.name || account.id, platform: this.platform, scopes: metaScopes })); }
  async syncMetrics(accessToken: string, accountId: string, from: Date, to: Date) { if (this.providerKey !== "meta_ads") throw new Error(`${this.providerKey} account connected; product metrics sync is not configured for this workspace.`); const url = new URL(`https://graph.facebook.com/v20.0/${accountId}/insights`); url.searchParams.set("fields", "date_start,impressions,clicks,actions,spend,action_values"); url.searchParams.set("time_range", JSON.stringify({ since: from.toISOString().slice(0, 10), until: to.toISOString().slice(0, 10) })); const body = await jsonRequest<{ data?: Array<{ date_start: string; impressions?: string; clicks?: string; spend?: string; actions?: Array<{ action_type: string; value: string }>; action_values?: Array<{ action_type: string; value: string }> }> }>(url.toString(), { headers: { authorization: `Bearer ${accessToken}` } }); return (body.data || []).map((row) => ({ externalId: accountId, date: row.date_start, impressions: Number(row.impressions || 0), clicks: Number(row.clicks || 0), conversions: Number(row.actions?.find((item) => item.action_type === "purchase" || item.action_type === "lead")?.value || 0), spend: Number(row.spend || 0), revenue: Number(row.action_values?.find((item) => item.action_type === "purchase")?.value || 0) })); }
}

export function providerKeyForPlatform(platform: Platform): ProviderKey { return platform === "Google Ads" ? "google_ads" : platform === "Meta Ads" ? "meta_ads" : platform === "Google Analytics" || platform === "GA4" ? "google_analytics" : platform === "Instagram" ? "meta_instagram" : platform === "Facebook" ? "meta_facebook" : platform === "YouTube" ? "google_youtube" : "google_analytics"; }
export function getProvider(providerKey: ProviderKey | Platform): MarketingProvider { const key = providerKey.includes("_") ? providerKey as ProviderKey : providerKeyForPlatform(providerKey as Platform); const config = providerConfiguration(key); if (!config.configured) throw new Error(`Provider configuration required: ${config.missing.join(", ")}.`); return key.startsWith("google_") ? new GoogleProvider(key) : new MetaProvider(key); }
